{
  "transactions": [
    {
      "id": "tx_00009Fuf8ub0x6WWTUVqKH",
      "created": "2016-12-31T10:38:51.403Z",
      "description": "Initial top up",
      "amount": 10000,
      "currency": "GBP",
      "merchant": null,
      "notes": "",
      "metadata": {
        "is_topup": "true",
        "stripe_charge_id": "ch_19WMJ4GFdNCyIQQUHih860zr"
      },
      "account_balance": 10000,
      "attachments": [],
      "category": "mondo",
      "is_load": true,
      "settled": "2016-12-31T10:38:51.403Z",
      "local_amount": 10000,
      "local_currency": "GBP",
      "updated": "2016-12-31T10:38:51.986Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260191600012",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009Fun1XJ5wQ6iIxfRMP",
      "created": "2016-12-31T12:07:10.04Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -1999,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 8001,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T07:31:20.97Z",
      "local_amount": -1999,
      "local_currency": "GBP",
      "updated": "2017-01-03T16:41:49.626Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260161231797400016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FuoftPDIXCY5DMFNp",
      "created": "2016-12-31T12:25:39.907Z",
      "description": "TESCO STORES 6363      BETHNAL GREEN GBR",
      "amount": -386,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093oy5b8P1wI27SIInB",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-04T18:17:40.751Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "271-275 Bethnal Green, London E2 6AH",
          "formatted": "271-275 Bethnal Green, London E2 6AH, United Kingdom",
          "address": "271-275 Bethnal Green",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 6AH",
          "latitude": 51.52647049999999,
          "longitude": -0.06577160000006188,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:53:40.463Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093oy5anUHi5HPLTWEL",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
          "google_places_id": "ChIJkdDADcYcdkgRO9PX-A164Co",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 7615,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T07:31:21.47Z",
      "local_amount": -386,
      "local_currency": "GBP",
      "updated": "2017-01-03T16:41:49.955Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260161231278398016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009Fv1ncyNZrQqq2pD3B",
      "created": "2016-12-31T14:52:43.57Z",
      "description": "AS NATURE INTENDED LTD LONDON        GBR",
      "amount": -1620,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QO55MkvoRWkHvSIj",
        "group_id": "grp_000093AWltUab6cy8CyYVN",
        "created": "2016-01-22T19:33:14.134Z",
        "name": "As Nature Intended",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/AsNatIntended/?size=large",
        "emoji": "🍁",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "132 Commercial St, London E1 6NG",
          "formatted": "132 Commercial St, London E1 6NG, United Kingdom",
          "address": "132 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6NG",
          "latitude": 51.52123873982813,
          "longitude": -0.07533307710783367,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-10-27T20:43:26.752Z",
        "metadata": {
          "created_for_merchant": "merch_000093AWltTsdj8t2u4BjF",
          "created_for_transaction": "tx_000094QO557rpANzQMftAX",
          "foursquare_category": "Organic Grocery",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "5479b214498e29745dbc0318",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJF7SkvrYcdkgR0Ur4CHCkl-0",
          "google_places_name": "As Nature Intended Ltd",
          "suggested_name": "As Nature Intended",
          "suggested_tags": "#groceries #food",
          "twitter_id": ""
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 5995,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T07:31:19.97Z",
      "local_amount": -1620,
      "local_currency": "GBP",
      "updated": "2017-01-03T16:41:48.964Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260161231729330002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009Fv2iQXuS8yAnrWnlh",
      "created": "2016-12-31T15:02:59.627Z",
      "description": "SAINSBURYS SACAT (4338 LONDON        GBR",
      "amount": -380,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094I6pylhvSmzxO8yWn",
        "group_id": "grp_000092JYbNZELEWvugCnyr",
        "created": "2016-01-18T19:42:19.78Z",
        "name": "Sainsbury's",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/@sainsburys/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Somewhere in 31-42 Bethnal Green Road, London E1 6HT",
          "formatted": "31-42 Bethnal Green Road, London E1 6HT, United Kingdom",
          "address": "31-42 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E1 6HT",
          "latitude": 51.5240488,
          "longitude": -0.07333549999998468,
          "zoom_level": 15,
          "approximate": true
        },
        "updated": "2016-04-03T09:58:03.406Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYbNXSRpSYIe325R",
          "created_for_transaction": "tx_000094I6pyYwgv6beZ8hft",
          "foursquare_category": "Convenience Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/conveniencestore_88.png",
          "foursquare_id": "4b42737af964a52034d425e3",
          "foursquare_website": "http://www.sainsburys.co.uk",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJDz5Fc7ccdkgRRxA49Z8E4w8",
          "google_places_name": "Sainsbury's",
          "suggested_name": "Sainsbury's Local",
          "suggested_tags": "#groceries",
          "twitter_id": "sainsburys",
          "website": "http://www.sainsburys.co.uk/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 5615,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T07:31:19.47Z",
      "local_amount": -380,
      "local_currency": "GBP",
      "updated": "2017-01-03T16:41:48.678Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260161231750932002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FvAPl1wrpEcSxBfGb",
      "created": "2016-12-31T16:29:15.413Z",
      "description": "THE GROCERY            LONDON        GBR",
      "amount": -2254,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094M8NMoWQKo1b1U2gD",
        "group_id": "grp_0000936WOlAeaqABlx6viL",
        "created": "2016-01-20T18:18:24.836Z",
        "name": "The Grocery",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/the_grocery/?size=large",
        "emoji": "☕️",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "52 Kingsland Rd, London E2 8DP",
          "formatted": "52 Kingsland Rd, London E2 8DP, United Kingdom",
          "address": "52 Kingsland Rd",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 8DP",
          "latitude": 51.528858,
          "longitude": -0.077726,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-06-06T06:16:30.571Z",
        "metadata": {
          "created_for_merchant": "merch_0000936WOl8WikcL3OvQjR",
          "created_for_transaction": "tx_000094M8NMWnUDkhoNxb5V",
          "foursquare_category": "Café",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/food/cafe_88.png",
          "foursquare_id": "566c18da498ea7697febe43c",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJe1Pt6LscdkgR1yaQghzm0OY",
          "google_places_name": "The Grocery",
          "suggested_name": "The Grocery Cafe",
          "suggested_tags": "#groceries #food",
          "twitter_id": "the_grocery",
          "website": "http://thegroceryshop.co.uk/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 3361,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T07:31:20.47Z",
      "local_amount": -2254,
      "local_currency": "GBP",
      "updated": "2017-01-03T16:41:49.247Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260161231931395009864",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FygHuDIcY86dafyIT",
      "created": "2017-01-02T09:10:32.197Z",
      "description": "BROCKWELL LIDO         LONDON SE24   GBR",
      "amount": -300,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000095yvsVhvjSPmswVoBd",
        "group_id": "grp_000095yvsVjLeAoGMJwQvh",
        "created": "2016-03-09T09:24:13.171Z",
        "name": "Brockwell Lido",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/brockwelllido/?size=large",
        "emoji": "🏊🏻",
        "category": "entertainment",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Dulwich Road, London SE24 0PA",
          "formatted": "Dulwich Road, London SE24 0PA, United Kingdom",
          "address": "Dulwich Road",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "SE24 0PA",
          "latitude": 51.45304669999999,
          "longitude": -0.1064506000000165,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-03-15T18:10:14.465Z",
        "metadata": {
          "created_for_merchant": "merch_000095yvsVhvjSPmswVoBd",
          "created_for_transaction": "tx_000095yvsU3TsMg5vFWFVp",
          "foursquare_category": "Pool",
          "foursquare_id": "4bbda3b307809521f8c6da91",
          "foursquare_website": "http://www.fusion-lifestyle.com/centres/Brockwell_Lido/facility/Outdoor_pool",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
          "google_places_id": "ChIJgXOw23IEdkgRoVksrQnM0KU",
          "google_places_name": "Brockwell Lido",
          "suggested_name": "Brockwell Lido",
          "suggested_tags": "#club #fun",
          "twitter_id": "brockwelllido",
          "website": "http://www.fusion-lifestyle.com/centres/Brockwell_Lido"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 3061,
      "attachments": [],
      "category": "entertainment",
      "is_load": false,
      "settled": "2017-01-03T09:10:20.52Z",
      "local_amount": -300,
      "local_currency": "GBP",
      "updated": "2017-01-03T21:51:04.192Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170102564096002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FyrIyt5pLVslMNOBl",
      "created": "2017-01-02T11:13:59.21Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -464,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 2597,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T10:42:45.817Z",
      "local_amount": -464,
      "local_currency": "GBP",
      "updated": "2017-01-03T23:00:55.552Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170102113054016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FyrnA3OsM9MEq9UQ5",
      "created": "2017-01-02T11:19:26.347Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -175,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 2422,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T10:42:46.817Z",
      "local_amount": -175,
      "local_currency": "GBP",
      "updated": "2017-01-03T23:00:56.085Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170102178064016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009Fyrvp6q7Gydt0tJpp",
      "created": "2017-01-02T11:21:00.2Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -185,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 2237,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-03T10:42:46.317Z",
      "local_amount": -185,
      "local_currency": "GBP",
      "updated": "2017-01-03T23:00:55.812Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170102351162016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009FytiCnfRCE5DSYe8X",
      "created": "2017-01-02T11:40:57.36Z",
      "description": "Top up",
      "amount": 10000,
      "currency": "GBP",
      "merchant": null,
      "notes": "",
      "metadata": {
        "is_topup": "true",
        "stripe_charge_id": "ch_19XUBNGFdNCyIQQU4TCJAa1S"
      },
      "account_balance": 12237,
      "attachments": [],
      "category": "mondo",
      "is_load": true,
      "settled": "2017-01-02T11:40:57.36Z",
      "local_amount": 10000,
      "local_currency": "GBP",
      "updated": "2017-01-02T11:40:57.679Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260192174801",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009G16CyMWkpntTjCPtx",
      "created": "2017-01-03T13:10:23.823Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -100,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 12137,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-04T11:03:43.53Z",
      "local_amount": -100,
      "local_currency": "GBP",
      "updated": "2017-01-04T14:03:18.043Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170103976124016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G1IIuNZfvGi11J6Ej",
      "created": "2017-01-03T15:25:55.927Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -185,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 11952,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-04T11:03:43.03Z",
      "local_amount": -185,
      "local_currency": "GBP",
      "updated": "2017-01-04T14:03:17.035Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170103551366016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G2zsdzMaAsIdXfIkj",
      "created": "2017-01-04T11:08:54.99Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -100,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 11852,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-05T10:40:16.703Z",
      "local_amount": -100,
      "local_currency": "GBP",
      "updated": "2017-01-05T14:34:21.997Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170104811884016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G3JPhYGFrz0N8St3h",
      "created": "2017-01-04T14:47:47.137Z",
      "description": "PRET A MANGER          LONDON        GBR",
      "amount": -239,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094e0qYfs6UGVwGp9vd",
        "group_id": "grp_000092JYpwxZY8LdQOp2rx",
        "created": "2016-01-29T09:18:51.179Z",
        "name": "Pret A Manger",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/pret/?size=large",
        "emoji": "☕️",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Whitechapel High Street, London E1 7PT",
          "formatted": "Whitechapel High Street, London E1 7PT, United Kingdom",
          "address": "Whitechapel High Street",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 7PT",
          "latitude": 51.5150302,
          "longitude": -0.07316209999999046,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:55:09.328Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpwwVc56LpI9HX7",
          "created_for_transaction": "tx_000094e0qYPD6RRmeY7qW9",
          "foursquare_category": "Sandwich Place",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/food/deli_88.png",
          "foursquare_id": "4b83d97af964a520751331e3",
          "foursquare_website": "https://plus.google.com/u/0/b/105098300116703889623/105098300116703889623",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png",
          "google_places_id": "ChIJXwSmLLUcdkgRJ8wWcmd_nKI",
          "google_places_name": "Pret A Manger",
          "suggested_name": "Pret A Manger",
          "suggested_tags": "#food",
          "twitter_id": "pret",
          "website": "http://www.pret.com/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 11613,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "2017-01-05T10:40:17.203Z",
      "local_amount": -239,
      "local_currency": "GBP",
      "updated": "2017-01-05T14:34:23.374Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170104634981009864",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G3cGUkuMKXBD0hhw1",
      "created": "2017-01-04T18:19:00.84Z",
      "description": "TESCO STORE 2092       BETHNAL GREEN GBR",
      "amount": -1040,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094RxVIyWe8lu0qzWZl",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-23T13:44:51.67Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Rd, London E2 0AN",
          "formatted": "361 Bethnal Green Rd, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Rd",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.52685304606054,
          "longitude": -0.06146762338187162,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:44:41.418Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000094RxVIiva8DagDCu5x",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 10573,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-05T05:10:45.68Z",
      "local_amount": -1040,
      "local_currency": "GBP",
      "updated": "2017-01-05T08:21:13.295Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170104686346016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G53HlHFJFlSofBKgD",
      "created": "2017-01-05T10:56:29.643Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -100,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 10473,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-06T11:14:03.36Z",
      "local_amount": -100,
      "local_currency": "GBP",
      "updated": "2017-01-06T14:53:58.175Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170105165434016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G5Rv13mxc8nxZ8cyH",
      "created": "2017-01-05T15:32:30.553Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -209,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 10264,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-06T11:14:02.86Z",
      "local_amount": -209,
      "local_currency": "GBP",
      "updated": "2017-01-06T14:53:57.694Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170105609196016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G5ehNIwl4Oo8wUS5h",
      "created": "2017-01-05T17:55:42.45Z",
      "description": "TESCO STORE 2092       BETHNAL GREEN GBR",
      "amount": -329,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094RxVIyWe8lu0qzWZl",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-23T13:44:51.67Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Rd, London E2 0AN",
          "formatted": "361 Bethnal Green Rd, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Rd",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.52685304606054,
          "longitude": -0.06146762338187162,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:44:41.418Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000094RxVIiva8DagDCu5x",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 9935,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-06T11:14:03.86Z",
      "local_amount": -329,
      "local_currency": "GBP",
      "updated": "2017-01-06T14:53:58.74Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170105268862016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G7jWtbjCjipO3a5s9",
      "created": "2017-01-06T17:59:15.61Z",
      "description": "SAINSBURYS SACAT (4338 LONDON        GBR",
      "amount": -85,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094I6pylhvSmzxO8yWn",
        "group_id": "grp_000092JYbNZELEWvugCnyr",
        "created": "2016-01-18T19:42:19.78Z",
        "name": "Sainsbury's",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/@sainsburys/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Somewhere in 31-42 Bethnal Green Road, London E1 6HT",
          "formatted": "31-42 Bethnal Green Road, London E1 6HT, United Kingdom",
          "address": "31-42 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E1 6HT",
          "latitude": 51.5240488,
          "longitude": -0.07333549999998468,
          "zoom_level": 15,
          "approximate": true
        },
        "updated": "2016-04-03T09:58:03.406Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYbNXSRpSYIe325R",
          "created_for_transaction": "tx_000094I6pyYwgv6beZ8hft",
          "foursquare_category": "Convenience Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/conveniencestore_88.png",
          "foursquare_id": "4b42737af964a52034d425e3",
          "foursquare_website": "http://www.sainsburys.co.uk",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJDz5Fc7ccdkgRRxA49Z8E4w8",
          "google_places_name": "Sainsbury's",
          "suggested_name": "Sainsbury's Local",
          "suggested_tags": "#groceries",
          "twitter_id": "sainsburys",
          "website": "http://www.sainsburys.co.uk/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 9850,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-09T10:18:05.713Z",
      "local_amount": -85,
      "local_currency": "GBP",
      "updated": "2017-01-09T10:49:57.865Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170106492404002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G7leH56WmJqQEwkWv",
      "created": "2017-01-06T18:23:00.207Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -494,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 9356,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-09T11:00:14.883Z",
      "local_amount": -494,
      "local_currency": "GBP",
      "updated": "2017-01-09T12:43:09.181Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170106782776016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G7suAnWMCDonDhwJd",
      "created": "2017-01-06T19:44:18.807Z",
      "description": "TfL Travel Charge      TFL.gov.uk/CP GBR",
      "amount": -150,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000092jBCaq2cHlL8pLVkP",
        "group_id": "grp_000092JYbUJtEgP9xND1Iv",
        "created": "2015-12-03T01:24:14.372Z",
        "name": "Transport for London",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tfl/?size=large",
        "emoji": "🚄",
        "category": "transport",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "42-50 Victoria Street, London SW1H 0TL",
          "formatted": "42-50 Victoria Street, London SW1H 0TL, United Kingdom",
          "address": "42-50 Victoria Street",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "SW1H 0TL",
          "latitude": 51.4976697,
          "longitude": -0.1351685,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-12-30T12:37:11.63Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYbUJXFziJUYDUS9",
          "created_for_transaction": "tx_000092jBCabVUKX3xYiolt",
          "foursquare_category": "Office",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/building/default_88.png",
          "foursquare_id": "4be929db88ed2d7fa0a3cc1d",
          "foursquare_website": "http://www.tfl.gov.uk",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
          "google_places_id": "ChIJ72B1j9sEdkgRIa40QIatrCM",
          "google_places_name": "Transport For London",
          "provider": "google",
          "provider_id": "ChIJ72B1j9sEdkgRoH1FijP-UoQ",
          "suggested_name": "Windsor House",
          "suggested_tags": "#transport #bus #train #tube",
          "twitter_id": "tfl",
          "website": "http://www.tfl.gov.uk"
        },
        "disable_feedback": false
      },
      "notes": "Active card check. TfL journey charges appear in your feed the following day.",
      "metadata": {
        "hide_amount": "false",
        "hide_transaction": "false",
        "notes": "Active card check. TfL journey charges appear in your feed the following day."
      },
      "account_balance": 9346,
      "attachments": [],
      "category": "transport",
      "is_load": false,
      "settled": "2017-01-09T11:00:15.383Z",
      "local_amount": -150,
      "local_currency": "GBP",
      "updated": "2017-01-09T12:43:09.043Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170106103277009864",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G7zeZvxphfDnUATUP",
      "created": "2017-01-06T20:59:55.9Z",
      "description": "BLUETIT                LONDON  N16   GBR",
      "amount": -4400,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000097fPBn3Aa5RoKa3Xmr",
        "group_id": "grp_000097fPBn4wTUriQ4sxY9",
        "created": "2016-04-28T19:02:37.547Z",
        "name": "Bluetit",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/bluetitlondon/?size=large",
        "emoji": "✂️",
        "category": "general",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "7 Stoke Newington Road, London N16 8BH",
          "formatted": "7 Stoke Newington Road, London N16 8BH, United Kingdom",
          "address": "7 Stoke Newington Road",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "N16 8BH",
          "latitude": 51.55083519999999,
          "longitude": -0.07527750000000001,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-06-01T07:34:12.08Z",
        "metadata": {
          "created_for_merchant": "merch_000097fPBn3Aa5RoKa3Xmr",
          "created_for_transaction": "tx_000097fPBmm9bMK9MkwBwv",
          "enriched_from_settlement": "tx_000098d98ZIjIoS8AxP59N",
          "foursquare_category": "Salon / Barbershop",
          "foursquare_id": "4e635c591495676d56214927",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
          "google_places_id": "ChIJP-NPEYwcdkgRBTpn4Ar8dCg",
          "google_places_name": "Blue Tit",
          "suggested_name": "Blue Tit",
          "suggested_tags": "#beauty #personal",
          "twitter_id": "bluetitlondon"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 4946,
      "attachments": [],
      "category": "general",
      "is_load": false,
      "settled": "2017-01-09T12:29:28.08Z",
      "local_amount": -4400,
      "local_currency": "GBP",
      "updated": "2017-01-09T17:11:58.111Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170106164901009250",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G90USMXQFoaghrIWn",
      "created": "2017-01-07T08:44:00.85Z",
      "description": "BROCKWELL LIDO         LONDON SE24   GBR",
      "amount": -300,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000095yvsVhvjSPmswVoBd",
        "group_id": "grp_000095yvsVjLeAoGMJwQvh",
        "created": "2016-03-09T09:24:13.171Z",
        "name": "Brockwell Lido",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/brockwelllido/?size=large",
        "emoji": "🏊🏻",
        "category": "entertainment",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Dulwich Road, London SE24 0PA",
          "formatted": "Dulwich Road, London SE24 0PA, United Kingdom",
          "address": "Dulwich Road",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "SE24 0PA",
          "latitude": 51.45304669999999,
          "longitude": -0.1064506000000165,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-03-15T18:10:14.465Z",
        "metadata": {
          "created_for_merchant": "merch_000095yvsVhvjSPmswVoBd",
          "created_for_transaction": "tx_000095yvsU3TsMg5vFWFVp",
          "foursquare_category": "Pool",
          "foursquare_id": "4bbda3b307809521f8c6da91",
          "foursquare_website": "http://www.fusion-lifestyle.com/centres/Brockwell_Lido/facility/Outdoor_pool",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
          "google_places_id": "ChIJgXOw23IEdkgRoVksrQnM0KU",
          "google_places_name": "Brockwell Lido",
          "suggested_name": "Brockwell Lido",
          "suggested_tags": "#club #fun",
          "twitter_id": "brockwelllido",
          "website": "http://www.fusion-lifestyle.com/centres/Brockwell_Lido"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 4646,
      "attachments": [],
      "category": "entertainment",
      "is_load": false,
      "settled": "2017-01-09T12:29:27.58Z",
      "local_amount": -300,
      "local_currency": "GBP",
      "updated": "2017-01-09T17:11:57.8Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170107746544002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G9mceDc1Onts8dNOD",
      "created": "2017-01-07T17:43:20.377Z",
      "description": "TAY DO RESTAURANT      LONDON        GBR",
      "amount": -1000,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000095zp5MFXhcKqnONBXl",
        "group_id": "grp_000095zp5MGxcKjKGlnoHp",
        "created": "2016-03-09T19:42:49.052Z",
        "name": "Tay Do Restaurant",
        "logo": "",
        "emoji": "🍴",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "65 Kingsland Road, London E2 8AG",
          "formatted": "65 Kingsland Road, London E2 8AG, United Kingdom",
          "address": "65 Kingsland Road",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 8AG",
          "latitude": 51.5297377,
          "longitude": -0.07762039999999998,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-03-15T17:54:00.021Z",
        "metadata": {
          "created_for_merchant": "merch_000095zp5MFXhcKqnONBXl",
          "created_for_transaction": "tx_000095zp5M2QUNkfYKzqBl",
          "foursquare_category": "Vietnamese Restaurant",
          "foursquare_id": "4addec49f964a5204e6621e3",
          "foursquare_website": "http://www.taydo.co.uk",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png",
          "google_places_id": "ChIJZXiD67scdkgRu0KA_THpup8",
          "google_places_name": "Tay Do Cafe",
          "suggested_name": "Tay Do Café",
          "suggested_tags": "#food",
          "twitter_id": ""
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 3646,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "2017-01-09T12:29:26.58Z",
      "local_amount": -1000,
      "local_currency": "GBP",
      "updated": "2017-01-09T17:11:57.161Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170107199283009864",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009G9n0wiWtZtJtihe6b",
      "created": "2017-01-07T17:47:43.96Z",
      "description": "THE GROCERY            LONDON        GBR",
      "amount": -528,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094M8NMoWQKo1b1U2gD",
        "group_id": "grp_0000936WOlAeaqABlx6viL",
        "created": "2016-01-20T18:18:24.836Z",
        "name": "The Grocery",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/the_grocery/?size=large",
        "emoji": "☕️",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "52 Kingsland Rd, London E2 8DP",
          "formatted": "52 Kingsland Rd, London E2 8DP, United Kingdom",
          "address": "52 Kingsland Rd",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 8DP",
          "latitude": 51.528858,
          "longitude": -0.077726,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-06-06T06:16:30.571Z",
        "metadata": {
          "created_for_merchant": "merch_0000936WOl8WikcL3OvQjR",
          "created_for_transaction": "tx_000094M8NMWnUDkhoNxb5V",
          "foursquare_category": "Café",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/food/cafe_88.png",
          "foursquare_id": "566c18da498ea7697febe43c",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJe1Pt6LscdkgR1yaQghzm0OY",
          "google_places_name": "The Grocery",
          "suggested_name": "The Grocery Cafe",
          "suggested_tags": "#groceries #food",
          "twitter_id": "the_grocery",
          "website": "http://thegroceryshop.co.uk/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 3118,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-09T12:29:27.08Z",
      "local_amount": -528,
      "local_currency": "GBP",
      "updated": "2017-01-09T17:11:57.499Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170107051973009864",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GBvuha5XvfHPukbqb",
      "created": "2017-01-08T18:36:52.1Z",
      "description": "AS NATURE INTENDED LTD LONDON        GBR",
      "amount": -1115,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QO55MkvoRWkHvSIj",
        "group_id": "grp_000093AWltUab6cy8CyYVN",
        "created": "2016-01-22T19:33:14.134Z",
        "name": "As Nature Intended",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/AsNatIntended/?size=large",
        "emoji": "🍁",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "132 Commercial St, London E1 6NG",
          "formatted": "132 Commercial St, London E1 6NG, United Kingdom",
          "address": "132 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6NG",
          "latitude": 51.52123873982813,
          "longitude": -0.07533307710783367,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-10-27T20:43:26.752Z",
        "metadata": {
          "created_for_merchant": "merch_000093AWltTsdj8t2u4BjF",
          "created_for_transaction": "tx_000094QO557rpANzQMftAX",
          "foursquare_category": "Organic Grocery",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "5479b214498e29745dbc0318",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJF7SkvrYcdkgR0Ur4CHCkl-0",
          "google_places_name": "As Nature Intended Ltd",
          "suggested_name": "As Nature Intended",
          "suggested_tags": "#groceries #food",
          "twitter_id": ""
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 2003,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-09T13:22:45.133Z",
      "local_amount": -1115,
      "local_currency": "GBP",
      "updated": "2017-01-10T01:01:58.284Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170108049346002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GDUZxoTgwXQmLkHK5",
      "created": "2017-01-09T12:40:00.48Z",
      "description": "THAI EXPRESS           LONDON        GBR",
      "amount": -680,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000095igvaLYKj0LdaeHQH",
        "group_id": "grp_000094OM1KFt2khhW74dBh",
        "created": "2016-03-01T13:21:19.131Z",
        "name": "Thai Express",
        "logo": "https://avatars.io/facebook/ThaiExpressUK/large",
        "emoji": "🍴",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "18 Mansell Street, London E1 8AA",
          "formatted": "18 Mansell Street, London E1 8AA, United Kingdom",
          "address": "18 Mansell Street",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 8AA",
          "latitude": 51.5137952,
          "longitude": -0.0736592,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-07-28T14:02:14.041Z",
        "metadata": {
          "created_for_merchant": "merch_000094OM1KFB5NNksQxGqX",
          "created_for_transaction": "tx_000095igvaByuJi0Smr9Sz",
          "foursquare_category": "Thai Restaurant",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/food/thai_88.png",
          "foursquare_id": "53dbf4de498e22feae3866b5",
          "foursquare_website": "",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png",
          "google_places_id": "ChIJx1JvIUsDdkgRrpsrCva7PU8",
          "google_places_name": "Thai Express (Aldgate)",
          "suggested_name": "Thai Express",
          "suggested_tags": "#food",
          "twitter_id": "",
          "website": "http://thaiexpress.co.uk/"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 1183,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "2017-01-10T11:00:01.233Z",
      "local_amount": -680,
      "local_currency": "GBP",
      "updated": "2017-01-10T12:09:48.601Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170109084276010495",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GE9JXcZOxLnBo1kFl",
      "created": "2017-01-09T20:16:26.843Z",
      "description": "TESCO STORES 5282      SPITALFIELDS  GBR",
      "amount": -250,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QFcQClZgSqiUUM53",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-22T17:58:24.903Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "116-118 Commercial St, London E1 6NF",
          "formatted": "116-118 Commercial St, London E1 6NF, United Kingdom",
          "address": "116-118 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6NF",
          "latitude": 51.52046009793695,
          "longitude": -0.07447957992553711,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:45:28.385Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000094QFcPxsT341WGcSQr",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJUYfbR7QcdkgRcFvETpeJAhI",
          "google_places_name": "Tesco Shoreditch Commercial St Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 933,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-10T11:00:01.733Z",
      "local_amount": -250,
      "local_currency": "GBP",
      "updated": "2017-01-10T12:09:48.883Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170109245322016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GEB19xYpqqeV6Cy3t",
      "created": "2017-01-09T20:35:31.93Z",
      "description": "FLOWER SUPERMARKET     LONDON        GBR",
      "amount": -711,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000096M2ph8LxfsVfYXUS9",
        "group_id": "grp_000092zSPxjnb07WSV6pEH",
        "created": "2016-03-20T13:00:30.351Z",
        "name": "Flowers Supermarket",
        "logo": "",
        "emoji": "🍎",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "London E2 7QB",
          "formatted": "London E2 7QB, United Kingdom",
          "address": "",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E2 7QB",
          "latitude": 55.378051,
          "longitude": -3.435973,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-05-27T09:27:46.906Z",
        "metadata": {
          "created_for_merchant": "merch_000092zSPxiNgHYcpviu7V",
          "created_for_transaction": "tx_000096M2pfinDDwmqmA8Vl",
          "enriched_from_settlement": "tx_0000984ABUB66can2zVzXt",
          "foursquare_category": "Flower Shop",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/flowershop_88.png",
          "foursquare_id": "4ac518f3f964a5209fae20e3",
          "foursquare_website": "http://www.columbiaroad.info",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJwQmOguI9fUgR4euyBxPlOHs",
          "google_places_name": "Waitrose Gretna Green Services",
          "suggested_name": "Columbia Road Flower Market",
          "suggested_tags": "#groceries #food",
          "twitter_id": "",
          "website": ""
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 222,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-11T05:18:48.253Z",
      "local_amount": -711,
      "local_currency": "GBP",
      "updated": "2017-01-11T07:00:43.086Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170109804136002515",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GFueYh9UgeNRs5f7J",
      "created": "2017-01-10T16:41:35.36Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -209,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-11T10:44:45.237Z",
      "local_amount": -209,
      "local_currency": "GBP",
      "updated": "2017-01-11T13:28:02.987Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170110667690016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GG0KUq8iUZta9ftPF",
      "created": "2017-01-10T17:45:11.807Z",
      "description": "THE CULPEPER           LONDON        GBR",
      "amount": -400,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QTCFvkYE7iEB2kSX",
        "group_id": "grp_000092WRp2QvXZ8UtkUfz7",
        "created": "2016-01-22T20:30:33.389Z",
        "name": "The Culpeper",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/theculpeper/?size=large",
        "emoji": "🍺",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "40 Commercial St, London E1 6LP",
          "formatted": "40 Commercial St, London E1 6LP, United Kingdom",
          "address": "40 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6LP",
          "latitude": 51.516989571705395,
          "longitude": -0.07314718030680911,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-02-03T18:23:50.37Z",
        "metadata": {
          "created_for_merchant": "merch_000092WRp2PrbVsUOjAa1p",
          "created_for_transaction": "tx_000094QTCFizJfPE2dyZ0b",
          "foursquare_category": "Pub",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/nightlife/pub_88.png",
          "foursquare_id": "539db859498eb12d43cf35e8",
          "foursquare_website": "http://www.theculpeper.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png",
          "google_places_id": "ChIJAfrz4lYxcEERCMgjl3xkNDI",
          "google_places_name": "The Culpeper",
          "suggested_name": "The Culpeper",
          "suggested_tags": "#food",
          "twitter_id": "theculpeper"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -400,
      "local_currency": "GBP",
      "updated": "2017-01-10T17:45:12.119Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170110889460012319",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GG0PDaKIX1ZVxWtw9",
      "created": "2017-01-10T17:46:03.027Z",
      "description": "THE CULPEPER           LONDON        GBR",
      "amount": -400,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QTCFvkYE7iEB2kSX",
        "group_id": "grp_000092WRp2QvXZ8UtkUfz7",
        "created": "2016-01-22T20:30:33.389Z",
        "name": "The Culpeper",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/theculpeper/?size=large",
        "emoji": "🍺",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "40 Commercial St, London E1 6LP",
          "formatted": "40 Commercial St, London E1 6LP, United Kingdom",
          "address": "40 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6LP",
          "latitude": 51.516989571705395,
          "longitude": -0.07314718030680911,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-02-03T18:23:50.37Z",
        "metadata": {
          "created_for_merchant": "merch_000092WRp2PrbVsUOjAa1p",
          "created_for_transaction": "tx_000094QTCFizJfPE2dyZ0b",
          "foursquare_category": "Pub",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/nightlife/pub_88.png",
          "foursquare_id": "539db859498eb12d43cf35e8",
          "foursquare_website": "http://www.theculpeper.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png",
          "google_places_id": "ChIJAfrz4lYxcEERCMgjl3xkNDI",
          "google_places_name": "The Culpeper",
          "suggested_name": "The Culpeper",
          "suggested_tags": "#food",
          "twitter_id": "theculpeper"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -400,
      "local_currency": "GBP",
      "updated": "2017-01-10T17:46:03.317Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170110650811012319",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GG3djeQApB0sl3iJV",
      "created": "2017-01-10T18:22:17.25Z",
      "description": "THE CULPEPER           LONDON        GBR",
      "amount": -400,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000094QTCFvkYE7iEB2kSX",
        "group_id": "grp_000092WRp2QvXZ8UtkUfz7",
        "created": "2016-01-22T20:30:33.389Z",
        "name": "The Culpeper",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/theculpeper/?size=large",
        "emoji": "🍺",
        "category": "eating_out",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "40 Commercial St, London E1 6LP",
          "formatted": "40 Commercial St, London E1 6LP, United Kingdom",
          "address": "40 Commercial St",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6LP",
          "latitude": 51.516989571705395,
          "longitude": -0.07314718030680911,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-02-03T18:23:50.37Z",
        "metadata": {
          "created_for_merchant": "merch_000092WRp2PrbVsUOjAa1p",
          "created_for_transaction": "tx_000094QTCFizJfPE2dyZ0b",
          "foursquare_category": "Pub",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/nightlife/pub_88.png",
          "foursquare_id": "539db859498eb12d43cf35e8",
          "foursquare_website": "http://www.theculpeper.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png",
          "google_places_id": "ChIJAfrz4lYxcEERCMgjl3xkNDI",
          "google_places_name": "The Culpeper",
          "suggested_name": "The Culpeper",
          "suggested_tags": "#food",
          "twitter_id": "theculpeper"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "eating_out",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -400,
      "local_currency": "GBP",
      "updated": "2017-01-10T18:22:17.641Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170110472947012319",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GHTTCRBb7DOmotwXp",
      "created": "2017-01-11T10:46:25.43Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -209,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -209,
      "local_currency": "GBP",
      "updated": "2017-01-11T10:46:25.906Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170111910112016103",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GHTWSaO0yH9tYK5pp",
      "created": "2017-01-11T10:47:00.34Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -209,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -209,
      "local_currency": "GBP",
      "updated": "2017-01-11T10:47:01.268Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170111936602016103",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GHTYGMmPwQGsCnUjh",
      "created": "2017-01-11T10:47:20.43Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -209,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 13,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "",
      "decline_reason": "INSUFFICIENT_FUNDS",
      "local_amount": -209,
      "local_currency": "GBP",
      "updated": "2017-01-11T10:47:20.811Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170111890546016103",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GHhic9xe006GS5ZxJ",
      "created": "2017-01-11T13:26:04.96Z",
      "description": "Top up",
      "amount": 20000,
      "currency": "GBP",
      "merchant": null,
      "notes": "",
      "metadata": {
        "is_topup": "true",
        "stripe_charge_id": "ch_19am74GFdNCyIQQUKAPeWjAB"
      },
      "account_balance": 20013,
      "attachments": [],
      "category": "mondo",
      "is_load": true,
      "settled": "2017-01-11T13:26:04.96Z",
      "local_amount": 20000,
      "local_currency": "GBP",
      "updated": "2017-01-11T13:26:05.863Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260196696486",
      "originator": false,
      "include_in_spending": false
    },
    {
      "id": "tx_00009GI0NFcq83CNa1gfM9",
      "created": "2017-01-11T16:55:07.083Z",
      "description": "TESCO STORES 4389      LONDON        GBR",
      "amount": -100,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093wo2Dm3yxTeWTH9P7",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2016-01-08T13:02:42.551Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "Aldgate East Tube, London E1 6BF",
          "formatted": "Aldgate East Tube, London E1 6BF, United Kingdom",
          "address": "Aldgate East Tube",
          "city": "London",
          "region": "Greater London",
          "country": "GBR",
          "postcode": "E1 6BF",
          "latitude": 51.515511546852984,
          "longitude": -0.07258147955394845,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:52:56.509Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093wo2Daif8PdXHJs2L",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJJTsMOrUcdkgRYpdNaFi6yrU",
          "google_places_name": "Tesco Express",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 19913,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-12T11:00:09.457Z",
      "local_amount": -100,
      "local_currency": "GBP",
      "updated": "2017-01-12T14:20:03.525Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170111719278016103",
      "originator": false,
      "include_in_spending": true
    },
    {
      "id": "tx_00009GIPBjBys8t8xKhlwn",
      "created": "2017-01-11T21:33:09.58Z",
      "description": "TESCO STORES-2092      BETHNAL GREEN GBR",
      "amount": -352,
      "currency": "GBP",
      "merchant": {
        "id": "merch_000093ccLbxZCTu80JHwxd",
        "group_id": "grp_000092JYpvjM7VZJ1X0Ukr",
        "created": "2015-12-29T19:17:31.614Z",
        "name": "Tesco",
        "logo": "https://mondo-logo-cache.appspot.com/twitter/tesco/?size=large",
        "emoji": "🍏",
        "category": "groceries",
        "online": false,
        "atm": false,
        "address": {
          "short_formatted": "361 Bethnal Green Road, London E2 0AN",
          "formatted": "361 Bethnal Green Road, London E2 0AN, United Kingdom",
          "address": "361 Bethnal Green Road",
          "city": "London",
          "region": "",
          "country": "GBR",
          "postcode": "E2 0AN",
          "latitude": 51.527023,
          "longitude": -0.061510999999995875,
          "zoom_level": 17,
          "approximate": false
        },
        "updated": "2016-01-29T14:32:24.136Z",
        "metadata": {
          "created_for_merchant": "merch_000092JYpvhEFProuw0nRJ",
          "created_for_transaction": "tx_000093ccLbgCF405YRoIZV",
          "foursquare_category": "Grocery Store",
          "foursquare_category_icon": "https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_88.png",
          "foursquare_id": "4fa002a07beb7ebce8fb6ffb",
          "foursquare_website": "http://www.tesco.com",
          "google_places_icon": "https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png",
          "google_places_id": "ChIJhwdQCsUcdkgR_n1MEuOyxAw",
          "google_places_name": "Tesco Bethnal Green Metro",
          "suggested_name": "Tesco Express",
          "suggested_tags": "#shopping #food",
          "twitter_id": "tesco",
          "website": "http://www.tesco.com"
        },
        "disable_feedback": false
      },
      "notes": "",
      "metadata": {},
      "account_balance": 19561,
      "attachments": [],
      "category": "groceries",
      "is_load": false,
      "settled": "2017-01-12T05:15:07.303Z",
      "local_amount": -352,
      "local_currency": "GBP",
      "updated": "2017-01-12T07:43:38.51Z",
      "account_id": "acc_00009FsRvpC42WhUgitVVx",
      "counterparty": {},
      "scheme": "gps_mastercard",
      "dedupe_id": "425230260170111836144016103",
      "originator": false,
      "include_in_spending": true
    }
  ]
}
